### PR TITLE
Made suggested changes on linters, navbar logo positioning and buttons.

### PR DESCRIPTION
**Pull request by M-Alamgir**
I have Made suggested changes regarding buttons, positioned the logo in the center, descriptive comments on a pull request, and fixed all linter problems.

### CODE REVIEW

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @ourandco**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [x] please fix all of the linters issues

- [x] the pull request should have a descriptive name and description

- [x] the New York times logo in the navbar is leaning to the right a little bit, place center it 

- [x] the hamburger and search icons in the navbar must be buttons

- [x] all buttons should have the cursor property set to pointer


---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Comment by M-Alamgir** [comment]
Thanks, Mahmoud Mohammad for your review,
I have made your suggested changes.

**Review by PhillipUg — CHANGES_REQUESTED** [review]
Hey team, 👋

You have done an amazing job implementing the project requirements of this project.

However, there are still some changes 👇 you need to implement to approve this request 🔍

### Changes Required ♻️ 

- [x] The hamburger and search icons and the link should be in the leftmost part of the Navbar. Similarly, the login elements should be in the rightmost part of the Navbar.

- [x] You have some overlapping content towards the bottom of your page. see image below
screenshot-ourandco github io-2020 11 26-12_39_50


### Optional Changes:
If you want to make your project even better 🔥💥, I left a few suggestions you can implement. 
These are completely [Optional]: 🦔

* [x] Page should have a fixed footer (it sticks to the bottom part of the screen) ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/positioning_and_floating_requirements.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))

> 

#### Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack as **Phillip Musiime**
I would be happy to help! 👩‍💻 

Happy coding 🤓

**Comment by M-Alamgir** [comment]
Hi, Phillip Musiime thanks for your review,
I have implemented your required changes and optional changes as well.

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
# Changes require
- [x] Now the over-lapping is gone but now you don't have content as present on the original page. Please have another look there

**Comment by ourandco** [comment]
Thanks Arslan Bisharat,
Can you please provide me with the screenshot of that content.

**Comment by M-Alamgir** [comment]
Thanks Arslan Bisharat,
I have added a Suggested Newsletter section.

**Review by MuriloRoque — APPROVED** [review]
## Status: Approved :green_circle: 

### Hello @ourandco :wave: 

### Thank you for making all of the requested changes. Your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Pull request merged**
